### ISSUE TITLE
Add SB MaterialAdmin Natives

### ISSUE THREAD

**Issue by panikajo** [DJPlaya/Kigen-AC-Redux#21]
please add this function on you're plugin
https://github.com/SB-MaterialAdmin/NewServer

**Comment by DJPlaya** [comment]
@panikajo 
Okay, now ime done with all initial Work related to banning and similar.
Before adding this, i need to know some Stuff first which i cannot find out myself because i do not speak Russian and i did not pay for hlmod.ru:
- Whats Material Admin?
- Is SB-MaterialAdmin an Addition or even Addon to MaterialAdmin?
- Is SB-MaterialAdmin something new or are there other Editions of it?
- Which Plugins need to be running in order to have the Natives available? For SB++, this is 'sbpp_main.smx' because it contains all Natives
- Is SB-MaterialAdmin supposed to run along with with SB2.0 or SB++?

**Comment by DJPlaya** [comment]
All Information needed got provided in a recent Issue in FFCR
