### ISSUE TITLE
kacr_eyes_antiwall affect server lag and drop down fps in CSS

### ISSUE THREAD

**Issue by Nerus87** [DJPlaya/Kigen-AC-Redux#41]
**Game**
CSS - Linux

**Metamod: Source version 1.10.7-dev**
Built from: https://github.com/alliedmodders/metamod-source/commit/6c8495f
Build ID: 971:6c8495f
Loaded As: Valve Server Plugin
Compiled on: Mar 28 2019
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

**SourceMod Version Information:**
SourceMod Version: 1.10.0.6460
SourcePawn Engine: 1.10.0.6460, jit-x86 (build 1.10.0.6460)
SourcePawn API: v1 = 5, v2 = 12
Compiled on: Jan  7 2020 13:39:09
Built from: https://github.com/alliedmodders/sourcemod/commit/2896435
Build ID: 6460:2896435
http://www.sourcemod.net/

**KACR build**
https://github.com/DJPlaya/Kigen-AC-Redux/commit/cb1bd15173abdad8c043917b209abac7def148cd

**Describe the Bug**
When kacr_eyes_antiwall enabled server drop fps and start lagging after the round start.
Server **sv**: is around 0-10 when the server population is around 30 players.

**To Reproduce**
Steps to reproduce the Behavior:
1. Compile plugin
2. Run SRCDS
3. Use `net_graph 5` to see vars.
4. See fps drop

**kacr_status output**
Nothing here

**Additional**
Nothing here

**Comment by DJPlaya** [comment]
Thanks for reporting.

The Eyecheck runs every Frame and checks the View from every Client to his Enemys.
In general, this could be Performance intense, i probably havent noticed performance Problems yet since i do not have Testers that run high traffic Servers.
Its on my todo to rewrite the Eyecheck, still i cant promise an performance improvement since it is an Performance intense Task in general. I will keep this in Mind anyway, maybe i can do periodically check the Clients and make something like a Suspicion System

**Comment by Nerus87** [comment]
Additional remember about [occluders](https://developer.valvesoftware.com/wiki/Func_occluder)
